### PR TITLE
A table containing information about planets of the solar system. (Made with pair programming approach)

### PR DESCRIPTION
**Pull request by Edjhernandez**

### CODE REVIEW

**Review by hendridg — CHANGES_REQUESTED** [review]
# :yellow_circle: Change Required :yellow_circle: 



Hi guys, really nice how you start the pair programming with this assignment, I suggest please in the description of `PR` put some screenshots of this feature, and a little description about this milestone, keep working! :muscle: 

image

**Comment by sazukeR** [comment]
https://github.com/sazukeR/tables/blob/develop/table-finished.png

**Comment by sazukeR** [comment]
https://github.com/sazukeR/tables/blob/develop/table-finished.png?raw=true

**Comment by sazukeR** [comment]
[https://github.com/sazukeR/tables/blob/develop/table-finished.png?raw=true](url)

**Comment by sazukeR** [comment]
thanks for the suggest, we added some changes following yours requirements.
here it a capture about how looks the html files when its executed in the browser.

**Pull request merged**
